//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TallerMecanicoEntities : DbContext
    {
        public TallerMecanicoEntities()
            : base("name=TallerMecanicoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<OrdenDeTrabajo> OrdenDeTrabajo { get; set; }
        public DbSet<Propietario> Propietario { get; set; }
        public DbSet<Repuesto> Repuesto { get; set; }
        public DbSet<RepuestoOT> RepuestoOT { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Vehiculo> Vehiculo { get; set; }
    }
}
