//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class OrdenDeTrabajo
    {
        public OrdenDeTrabajo()
        {
            this.RepuestoOT = new HashSet<RepuestoOT>();
        }
    
        public int idOrdenDeTrabajo { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public string detalleFalla { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public int idVehiculo { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public int idUsuario { get; set; }
        public Nullable<double> total { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
        public virtual ICollection<RepuestoOT> RepuestoOT { get; set; }
    }
}
