//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Propietario
    {
        public Propietario()
        {
            this.Vehiculo = new HashSet<Vehiculo>();
        }
    
        public int idPropietario { get; set; }
        [Required(ErrorMessage = "campo obligatorio")]
        [Range(5000000, 50000000, ErrorMessage = "Ingrese un numero de DNI valido")]
        public string dni { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]     
        [RegularExpression("([A-Za-z]{1,20})", ErrorMessage = "solo acepta letras")]
        public string nombre { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [RegularExpression("([A-Za-z]{1,20})", ErrorMessage = "solo acepta letras")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "Invalid")]
        public string apellido { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public string direccion { get; set; }
        [RegularExpression("([11]+[0-9]{8})", ErrorMessage = "Inserte un numero valido que empiece con 11")]     
        public string telefono { get; set; }
        [EmailAddress(ErrorMessage = "El email no tiene el formato correcto")]
        public string mail { get; set; }
       
        public string LetAB
        {
            get { return this.nombre +" "+ this.apellido; }
        }

    
        public virtual ICollection<Vehiculo> Vehiculo { get; set; }

        

    }
}
