//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class RepuestoOT
    {
        public int idRepuestoOT { get; set; }
        public int idOrdenDeTrabajo { get; set; }
        public int idRepuesto { get; set; }
        [Range(1, 100, ErrorMessage = "La cantidad tiene que estar entre 1 y 100")]
        public int cantidadDeRepuesto { get; set; }
        [Range(1, 100, ErrorMessage = "La cantidad tiene que estar entre 1 y 200")]
        public double cantidadHorasTrabajo { get; set; }
       
    
        public virtual OrdenDeTrabajo OrdenDeTrabajo { get; set; }
        public virtual Repuesto Repuesto { get; set; }
    }
}
