//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.OrdenDeTrabajo = new HashSet<OrdenDeTrabajo>();
        }
    
        public int idUsuario { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public string nombreUsuario { get; set; }
        [Required(ErrorMessage = "Ingrese una password de minimo 5 y maximo 10 caracteres")]
        [MaxLength(10), MinLength(3)]
        public string password { get; set; }
       [Required(ErrorMessage = "El campo {0} es requerido")]
        public int idRol { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public string nombreCompleto { get; set; }
        
        public virtual ICollection<OrdenDeTrabajo> OrdenDeTrabajo { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
